name: DevDeploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    env:
      REACT_APP_BACKEND_API: https://dev.algolytic.pro/api/v1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies+Build+Deploy
        run: |
          cd algolytic-frontend
          npm i
          npm run build
          cp -r ./build/* /var/www/dev.algolytic.pro