name: DevDeploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          cd algolytic-frontend
          npm i

      - name: Build
        run: |
          cd algolytic-frontend
          npm run build