name: DevDeploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: ls

      - name: entering into project folder
        run: cd algolytic-frontend

      - name: test1
        run: ls

      - name: Install dependencies
        run: npm i

      - name: Build frontend
        run: npm run build